routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\StockController as AdminStockController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\EmailNotificationController as AdminEmailNotificationController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\ShippingController as AdminShippingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\WishlistController;
use App\Http\Controllers\User\EmailNotificationController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\CategoryController;

if (App::environment('production')) {
    URL::forceScheme('https');
}


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Route Admin
 */

Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.home');

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [AdminRoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_read');

        Route::get('/create', [AdminRoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [AdminRoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_create');

        Route::put('/{id}', [AdminRoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('/{id}/edit', [AdminRoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_update');

        Route::delete('/{id}', [AdminRoleController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:role_delete');

        Route::get('/{id}', [AdminRoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_read');
    });

    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [AdminUserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_read');

        Route::get('/create', [AdminUserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::get('/{id}', [AdminUserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_read');

        Route::post('/', [AdminUserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_create');

        Route::put('/{id}', [AdminUserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('/{id}/edit', [AdminUserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_update');

        Route::delete('/{id}', [AdminUserController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:user_delete', 'check.delete.user');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [AdminCategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_read');

        Route::get('/list', [AdminCategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_read');

        Route::post('/', [AdminCategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_create');

        Route::get('/create', [AdminCategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::get('/{id}', [AdminCategoryController::class, 'show'])
            ->name('show')
            ->middleware('permission:category_read');

        Route::delete('/{id}', [AdminCategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');

        Route::put('/{id}', [AdminCategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::get('/{id}/edit', [AdminCategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_update');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [AdminProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_read');

        Route::get('/create', [AdminProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/{id}', [AdminProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_read');

        Route::post('/', [AdminProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_create');

        Route::put('/{id}', [AdminProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::get('/{id}/edit', [AdminProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_update');

        Route::delete('/{id}', [AdminProductController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:product_delete');
    });

    Route::name('stocks.')->prefix('stocks')->group(function (){
        Route::get('/', [AdminStockController::class, 'index'])
            ->name('index')
            ->middleware('permission:stock_read');
        Route::get('/create', [AdminStockController::class, 'create'])
            ->name('create')
            ->middleware('permission:stock_create');
        Route::post('/', [AdminStockController::class, 'store'])
            ->name('store')
            ->middleware('permission:stock_create');
        Route::put('/update/{id}', [AdminStockController::class, 'update'])
            ->name('update')
            ->middleware('permission:stock_update');
        Route::get('/{id}/edit', [AdminStockController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:stock_update');
        Route::get('/{id}', [AdminStockController::class, 'show'])
            ->name('show')
            ->middleware('permission:stock_read');
        Route::delete('/{id}', [AdminStockController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:stock_delete');
    });

    Route::name('coupons.')->prefix('coupons')->group(function () {
        Route::get('/', [AdminCouponController::class, 'index'])
            ->name('index')
            ->middleware('permission:coupon_read');
        Route::get('/create', [AdminCouponController::class, 'create'])
            ->name('create')
            ->middleware('permission:coupon_create');
        Route::post('/', [AdminCouponController::class, 'store'])
            ->name('store')
            ->middleware('permission:coupon_create');
        Route::put('/update/{id}', [AdminCouponController::class, 'update'])
            ->name('update')
            ->middleware('permission:coupon_update');
        Route::get('/{id}/edit', [AdminCouponController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:coupon_update');
        Route::get('/{id}', [AdminCouponController::class, 'show'])
            ->name('show')
            ->middleware('permission:coupon_read');
        Route::delete('/{id}', [AdminCouponController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:coupon_delete');
    });

    Route::name('emails.')->prefix('emails')->group(function () {
        Route::get('/', [AdminEmailNotificationController::class, 'index'])->name('index');
        Route::get('/create', [AdminEmailNotificationController::class, 'create'])->name('create');
        Route::put('/update/{id}', [AdminEmailNotificationController::class, 'update'])->name('update');
        Route::get('/{id}/edit', [AdminEmailNotificationController::class, 'edit'])->name('edit');
        Route::delete('/{id}', [AdminEmailNotificationController::class, 'destroy'])->name('destroy');
    });

    Route::name('orders.')->prefix('orders')->group(function () {
        Route::get('/', [AdminOrderController::class, 'index'])
            ->name('index')
            ->middleware('permission:order_read');
        Route::get('/create', [AdminOrderController::class, 'create'])
            ->name('create')
            ->middleware('permission:order_create');
        Route::post('/', [AdminOrderController::class, 'store'])
            ->name('store')
            ->middleware('permission:order_create');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Permission;

class Role extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name',
    ];

    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    public function permissions()
    {
        return $this->belongsToMany(
            Permission::class,
            'permission_role',
            'role_id',
            'permission_id'
        );
    }

    public function users()
    {
        return $this->belongsToMany(
            User::class,
            'role_user',
            'role_id',
            'user_id'
        );
    }

    public function scopeWithName($query, $name)
    {
        return $query->where('name', 'Like', '%' . $name . '%');
    }

    public function scopeWithoutSuperAdmin($query)
    {
        return $query->where('name', '!=', 'super-admin');
    }

    public function addPermission($permissionId)
    {
        return $this->permissions()->attach($permissionId);
    }

    public function syncPermission($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Role\StoreRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected RoleService $roleService;
    protected PermissionService $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $roles = $this->roleService->search($request);
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRoleRequest $request
     * @return RedirectResponse
     */
    public function store(StoreRoleRequest $request)
    {
        $this->roleService->create($request);
        return redirect()->route('roles.index')->with('message', 'Create Success!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $role = $this->roleService->findById($id);
        return view('admin.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit(int $id)
    {
        $permissionId = $this->roleService->getPermissionId($id);
        $role = $this->roleService->findById($id);
        return view('admin.roles.edit', compact('role', 'permissionId'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRoleRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(UpdateRoleRequest $request, int $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route('roles.index')->with('message', 'Update Success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index')->with('message', 'Delete Success!');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'roles'
])
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-header">
                        <h2 class="mb-0 text-dark text-center">
                            Create Role
                        </h2>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('roles.store') }}" method="POST">
                            @csrf
                            <div class="form-group mb-3">
                                <label class="text-dark">
                                    <h6 class="m-0">Name <span class="text-danger">*</span></h6>
                                </label>
                                <input type="text" class="form-control" name="display_name"
                                       value="{{ old('display_name') }}" placeholder="Display name ...">
                                @error('display_name')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="text-dark mb-2">
                                    <h6 class="m-0">Permission</h6>
                                </label>
                                <div class="row">
                                    @foreach($permissions as $group => $permissionGroup)
                                        <div class="col-3">
                                            <div class="container-fluid">
                                                <div class="text-dark font-weight-bold">{{ ucfirst($group) }}</div>
                                                @foreach($permissionGroup as $permission)
                                                    <div class="container pl-0">
                                                        <div class="form-check">
                                                            <label class="form-check-label text-dark font-weight-bold">
                                                                <input class="form-check-input" type="checkbox"
                                                                       name="permission_id[]"
                                                                       id="{{$permission->group_name}}"
                                                                       value="{{$permission->id}}">
                                                                {{$permission->display_name}}
                                                                <span class="form-check-sign">
                                                                <span class="check"></span>
                                                            </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div>
                                <a href="{{ route('roles.index') }}" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'roles'
])
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-header">
                        <h2 class="mb-0 text-dark text-center">
                            Edit Role
                        </h2>
                    </div>
                    <div class="card-body">
                        <form action="{{route('roles.update', $role->id)}}" method="POST">
                            @csrf
                            @method("PUT")
                            <div class="form-group mb-3">
                                <label class="text-dark">
                                    <h6 class="m-0">Name <span class="text-danger">*</span></h6>
                                </label>
                                <input type="text" class="form-control" name="display_name"
                                       value="{{ old('display_name', $role->display_name) }}" placeholder="Name ...">
                                @error('display_name')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="text-dark mb-2">
                                    <h6 class="m-0">Permission</h6>
                                </label>
                                <div class="row">
                                    @foreach($permissions as $group => $permissionGroup)
                                        <div class="col-3">
                                            <div class="container-fluid">
                                                <div class="text-dark font-weight-bold">{{ ucfirst($group) }}</div>
                                                @foreach($permissionGroup as $permission)
                                                    <div class="container pl-0">
                                                        <div class="form-check">
                                                            <label class="form-check-label text-dark font-weight-bold">
                                                                <input class="form-check-input" type="checkbox"
                                                                       {{ $permissionId->contains($permission->id) ? 'checked' : '' }}
                                                                       name="permission_id[]"
                                                                       id="{{ $permission->group_name }}" value="{{ $permission->id }}">
                                                                {{ $permission->display_name }}
                                                                <span class="form-check-sign">
                                                                <span class="check"></span>
                                                            </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div>
                                <a href="{{ route('roles.index') }}" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'roles'
])
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                @if (session('message'))
                    <div id="notification" class="alert alert-success font-weight-bold">
                        {{ session('message') }}
                    </div>
                @endif
                <div class="card shadow">
                    <div class="card-header border-0 pb-2">
                        <div class="row align-items-center">
                            <form method="GET" class="col-11 d-flex justify-content-end">
                                <div class="input-group no-border w-75 m-0">
                                    <input type="text" name="search" value="{{ request('search') ?? '' }}"
                                        class="form-control" placeholder="Search...">
                                    <button class="btn m-0" type="submit">
                                        <div class="input-group-append">
                                            <i class="nc-icon nc-zoom-split"></i>
                                        </div>
                                    </button>
                                </div>
                            </form>
                            <div class="col-1">
                                @hasPermission('role_create')
                                    <a href="{{ route('roles.create') }}"
                                       class="btn btn-sm btn-primary">
                                        <i class="fas fa-plus fa-2x"></i>
                                    </a>
                                @endhasPermission
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col" class="w-160">Name</th>
                                <th scope="col" class="text-center">Permission</th>
                                <th scope="col" class="text-center w-160">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($roles as $role)
                                @if ($role->name != 'super-admin')
                                <tr>
                                    <td>{{ $loop->iteration + $roles->firstItem() - 1 }}</td>
                                    <td>{{ $role->display_name }}</td>
                                    <td>
                                        @foreach($role->permissions as $item)
                                            {{ $item->display_name }}{{ $loop->last ? '.' : ',' }}
                                        @endforeach
                                    </td>
                                    <td>
                                        <div class="container">
                                            <div class="d-flex justify-content-center">
                                                <form action="{{ route('roles.destroy', $role->id) }}"
                                                      method="POST" id="form-{{ $role->id }}">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                @hasPermission('role_delete')
                                                    <button class="btn btn-danger p-2 w-icon"
                                                            onclick="deleteRole({{ $role->id }})">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>
                                                @endhasPermission
                                                @hasPermission('role_update')
                                                    <a href="{{ route('roles.edit', $role->id) }}"
                                                       class="btn btn-warning ml-2 p-2 w-icon">
                                                        <i class="far fa-edit text-white"></i>
                                                    </a>
                                                @endhasPermission
                                                @hasPermission('role_read')
                                                    <a href="{{ route('roles.show', $role->id) }}"
                                                       class="btn btn-info ml-2 p-2 w-icon">
                                                        <i class="fal fa-info-square"></i>
                                                    </a>
                                                @endhasPermission
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endif
                            @endforeach
                            </tbody>
                        </table>
                        <div class="container justify-content-center">
                            {{$roles->appends(request()->all())->links()}}
                        </div>
                    </div>
                    <div class="card-footer py-3">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            @if(count($roles) <= 0)
                                <h6 class="container text-center font-weight-bold mb-0">-- NOT FOUND DATA --</h6>
                            @endif
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        function deleteRole(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger mr-3'
                },
                buttonsStyling: false
            })
            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
            }).then((result) => {
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('form-' + id).submit();
                    swalWithBootstrapButtons.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success',
                    )
                } else if (
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your role file is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'roles'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">
                            Name: {{$role->display_name}}
                        </h3>
                        <h6 class="card-collapse ml-4">Permission:</h6>
                        <p class="card-text ml-4">
                            @foreach($role->permissions as $permission)
                                {{$permission->display_name}},
                            @endforeach
                        </p>
                        <div>
                            <a href="{{ route('roles.index') }}" class="btn btn-danger">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection