routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\StockController as AdminStockController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\EmailNotificationController as AdminEmailNotificationController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\ShippingController as AdminShippingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\WishlistController;
use App\Http\Controllers\User\EmailNotificationController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\CategoryController;

if (App::environment('production')) {
    URL::forceScheme('https');
}


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Route Admin
 */

Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.home');

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [AdminRoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_read');

        Route::get('/create', [AdminRoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [AdminRoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_create');

        Route::put('/{id}', [AdminRoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('/{id}/edit', [AdminRoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_update');

        Route::delete('/{id}', [AdminRoleController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:role_delete');

        Route::get('/{id}', [AdminRoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_read');
    });

    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [AdminUserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_read');

        Route::get('/create', [AdminUserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::get('/{id}', [AdminUserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_read');

        Route::post('/', [AdminUserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_create');

        Route::put('/{id}', [AdminUserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('/{id}/edit', [AdminUserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_update');

        Route::delete('/{id}', [AdminUserController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:user_delete', 'check.delete.user');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [AdminCategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_read');

        Route::get('/list', [AdminCategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_read');

        Route::post('/', [AdminCategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_create');

        Route::get('/create', [AdminCategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::get('/{id}', [AdminCategoryController::class, 'show'])
            ->name('show')
            ->middleware('permission:category_read');

        Route::delete('/{id}', [AdminCategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');

        Route::put('/{id}', [AdminCategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::get('/{id}/edit', [AdminCategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_update');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [AdminProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_read');

        Route::get('/create', [AdminProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/{id}', [AdminProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_read');

        Route::post('/', [AdminProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_create');

        Route::put('/{id}', [AdminProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::get('/{id}/edit', [AdminProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_update');

        Route::delete('/{id}', [AdminProductController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:product_delete');
    });

    Route::name('stocks.')->prefix('stocks')->group(function (){
        Route::get('/', [AdminStockController::class, 'index'])
            ->name('index')
            ->middleware('permission:stock_read');
        Route::get('/create', [AdminStockController::class, 'create'])
            ->name('create')
            ->middleware('permission:stock_create');
        Route::post('/', [AdminStockController::class, 'store'])
            ->name('store')
            ->middleware('permission:stock_create');
        Route::put('/update/{id}', [AdminStockController::class, 'update'])
            ->name('update')
            ->middleware('permission:stock_update');
        Route::get('/{id}/edit', [AdminStockController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:stock_update');
        Route::get('/{id}', [AdminStockController::class, 'show'])
            ->name('show')
            ->middleware('permission:stock_read');
        Route::delete('/{id}', [AdminStockController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:stock_delete');
    });

    Route::name('coupons.')->prefix('coupons')->group(function () {
        Route::get('/', [AdminCouponController::class, 'index'])
            ->name('index')
            ->middleware('permission:coupon_read');
        Route::get('/create', [AdminCouponController::class, 'create'])
            ->name('create')
            ->middleware('permission:coupon_create');
        Route::post('/', [AdminCouponController::class, 'store'])
            ->name('store')
            ->middleware('permission:coupon_create');
        Route::put('/update/{id}', [AdminCouponController::class, 'update'])
            ->name('update')
            ->middleware('permission:coupon_update');
        Route::get('/{id}/edit', [AdminCouponController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:coupon_update');
        Route::get('/{id}', [AdminCouponController::class, 'show'])
            ->name('show')
            ->middleware('permission:coupon_read');
        Route::delete('/{id}', [AdminCouponController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:coupon_delete');
    });

    Route::name('emails.')->prefix('emails')->group(function () {
        Route::get('/', [AdminEmailNotificationController::class, 'index'])->name('index');
        Route::get('/create', [AdminEmailNotificationController::class, 'create'])->name('create');
        Route::put('/update/{id}', [AdminEmailNotificationController::class, 'update'])->name('update');
        Route::get('/{id}/edit', [AdminEmailNotificationController::class, 'edit'])->name('edit');
        Route::delete('/{id}', [AdminEmailNotificationController::class, 'destroy'])->name('destroy');
    });

    Route::name('orders.')->prefix('orders')->group(function () {
        Route::get('/', [AdminOrderController::class, 'index'])
            ->name('index')
            ->middleware('permission:order_read');
        Route::get('/create', [AdminOrderController::class, 'create'])
            ->name('create')
            ->middleware('permission:order_create');
        Route::post('/', [AdminOrderController::class, 'store'])
            ->name('store')
            ->middleware('permission:order_create');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'parent_id'
    ];

    public function products()
    {
        return $this->belongsToMany(
            Product::class,
            'category_product',
            'category_id',
            'product_id',
        );
    }

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'Like', '%' . $name . '%') : null;
    }

    public function scopeCategoryIsNullParent($query)
    {
        return $query->whereNull('parent_id');
    }

    public function getParentNameAttribute()
    {
        return $this->parentCategory ? $this->parentCategory->name : null;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Http\Resources\Category\CategoryResource;
use App\Services\CategoryService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    protected CategoryService $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.categories.index');
    }

    public function list(Request $request)
    {
        $categoriesByPage = $this->categoryService->search($request);
        return view('admin.categories.list', compact('categoriesByPage'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCategoryRequest $request
     * @return JsonResponse
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = $this->categoryService->create($request);
        $categoryResource = new CategoryResource($category);

        return $this->sentSuccessResponse(
            $categoryResource,
            'Create category successfully!',
            Response::HTTP_OK
        );
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return JsonResponse
     */
    public function show(int $id)
    {
        $category = $this->categoryService->findById($id);
        $categoryResource = new CategoryResource($category);

        return $this->sentSuccessResponse(
            $categoryResource,
            'Success!',
            Response::HTTP_OK
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return JsonResponse
     */
    public function edit(int $id)
    {
        $category = $this->categoryService->findById($id);
        $categoryResource = new CategoryResource($category);

        return $this->sentSuccessResponse(
            $categoryResource,
            'Success!',
            Response::HTTP_OK
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCategoryRequest $request
     * @param int $id
     * @return JsonResponse
     */
    public function update(UpdateCategoryRequest $request, int $id)
    {
        $category = $this->categoryService->update($request, $id);
        $categoryResource = new CategoryResource($category);
        return $this->sentSuccessResponse(
            $categoryResource,
            'Update category successfully!',
            Response::HTTP_OK
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return JsonResponse
     */
    public function destroy(int $id)
    {
        DB::beginTransaction();
            $this->categoryService->delete($id);
            $this->categoryService->deleteParent($id);
        DB::commit();
        return $this->sentSuccessResponse(
            '',
            'Delete category successfully!',
            Response::HTTP_OK
        );
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Services\ProductService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected ProductService $productService;

    /**
     * @param ProductService $productService
     */
    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function index($page)
    {
        if ($page == 'All Products') {
            $productByCate = $this->productService->getListProductByCategory(null);
        }
        else {
            $productByCate = $this->productService->getListProductByCategory($page);
        }
        return view('user.categories.index', compact('productByCate', 'page'));
    }

    public function list($page)
    {
        if ($page == 'allProduct') {
            $products = $this->productService->getListProductByCategory(null);
        }
        else {
            $products = $this->productService->getListProductByCategory($page);
        }
        return view('user.categories.list', compact('products'));
    }
}

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'categories'
])
@section('content')
{{--Create modal--}}
<div class="modal fade" id="CreateCategory" tabindex="-1" role="dialog"
 aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Create category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="CreateCategory" enctype="multipart/form-data" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="form-group">
                                <label class="text-dark">
                                    <h6 class="m-0">Name Category</h6>
                                </label>
                                <input type="text" class="form-control" id="nameCategory"
                                       name="name" placeholder="Name ...">
                            </div>
                            <span class="text-danger name_error_create" id="error"></span>
                            <div class="form-group">
                                <label class="text-dark">
                                    <h6 class="m-0">Parent name</h6>
                                </label>
                                <select class="form-control" id="parentIdCategory" name="parent_id">
                                    <option value="">-- Null --</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-3" data-dismiss="modal">
                    Close
                </button>
                <button type="submit" id="btn-create" class="btn btn-primary"
                        data-action="{{ route('categories.store') }}">
                    Submit
                </button>
            </div>
        </div>
    </div>
</div>
{{--Edit Modal--}}
<div class="modal fade" id="EditCategory" tabindex="-1" role="dialog"
 aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="EditCategory" enctype="multipart/form-data" method="POST">
                @csrf
                @method("PUT")
                <div class="modal-body">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="form-group">
                                <label class="text-dark">
                                    <h6 class="m-0">Name Category</h6>
                                </label>
                                <input type="text" class="form-control" id="nameUpdate"
                                       name="name" placeholder="Name ...">
                            </div>
                            <span class="text-danger name_error_update" id="error"></span>
                            <div class="form-group">
                                <label class="text-dark">
                                    <h6 class="m-0">Parent name</h6>
                                </label>
                                <select class="form-control form-control-lg rounded" id="parentIdUpdate" name="parent_id">
                                    <option value="">-- Null --</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-3" data-dismiss="modal">
                    Close
                </button>
                <button type="button" id="btn-update" class="btn btn-primary" autofocus>
                    Save changes
                </button>
            </div>
        </div>
    </div>
</div>
{{--Show Modal--}}
<div class="modal fade" id="ShowCategory" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Show category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="form-group row align-items-center">
                                <label class="text-dark col-4 mb-0">
                                    <h6 class="m-0">Name Category</h6>
                                </label>
                                <h4 id="nameShow" class="col-8 p-0 m-0"></h4>
                            </div>
                            <div class="form-group row align-items-center">
                                <label class="text-dark col-4 mb-0 pr-0">
                                    <h6 class="m-0">Parent name</h6>
                                </label>
                                <select disabled class="form-control form-control-lg col-7 mr-2 rounded" id="parentIdShow" name="parent_id">
                                    <option value="">-- Null --</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-3" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-header border-0 pb-2">
                    <div id="success_message" class="m-0 rounded"></div>
                    <div class="row align-items-center">
                        <form method="POST" class="col-11 d-flex justify-content-end">
                            <div class="input-group no-border m-0 w-75">
                                <input type="search" name="search" id="search"
                                       class="form-control" placeholder="Search..."
                                       value="{{ request('search') }}">
                                <button class="btn m-0" id="btn-search">
                                    <div class="input-group-append">
                                        <i class="nc-icon nc-zoom-split"></i>
                                    </div>
                                </button>
                            </div>
                        </form>
                        <div class="col-1 text-right">
                            <a data-bs-toggle="modal" data-toggle="modal"
                               data-target="#CreateCategory" class="btn btn-sm btn-primary">
                                <i class="fas fa-plus text-white fa-2x"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div id="list" data-action="{{ route('categories.list') }}">
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

@push('scripts')
    <script src="{{ asset('paper/js/admin/category.js') }}"></script>
@endpush

resources/views/admin/categories/list.blade.php
<div id="list" data-action="{{ route('categories.list') }}">
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Parent name</th>
                <th scope="col" class="text-center w-160">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categoriesByPage as $category)
                <tr>
                    <td>{{ $loop->iteration + $categoriesByPage->firstItem() - 1 }}</td>
                    <td>{{ $category->name }}</td>
                    <td>
                        @if($category->ParentName != null)
                            {{ $category->ParentName }}
                        @else
                            <h6 class="mb-0 badge badge-danger p-1">NULL</h6>
                        @endif
                    </td>
                    <td>
                        <div class="container">
                            <div class="d-flex justify-content-center">
                                @hasPermission('category_delete')
                                    <button class="btn btn-danger p-2 w-icon btn-delete-category"
                                            id="btn-delete"
                                            data-action="{{ route('categories.destroy', $category->id) }}">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                @endhasPermission
                                @hasPermission('category_update')
                                    <a class="btn btn-warning ml-2 p-2 w-icon" data-bs-toggle="modal" id="btn-edit"
                                       data-toggle="modal" data-target="#EditCategory"
                                       data-action="{{ route('categories.edit',$category->id) }}"
                                       data-update="{{ route('categories.update',$category->id) }}">
                                        <i class="far fa-edit text-white"></i>
                                    </a>
                                @endhasPermission
                                @hasPermission('category_read')
                                    <a data-action="{{ route('categories.show', $category->id) }}"
                                       data-toggle="modal" data-target="#ShowCategory" data-bs-toggle="modal"
                                       class="btn btn-info ml-2 p-2 w-icon" id="btn-show">
                                        <i class="fal fa-info-square text-white"></i>
                                    </a>
                                @endhasPermission
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="container justify-content-center">
            {{ $categoriesByPage->appends(request()->all())->links() }}
        </div>
    </div>
    <div class="card-footer py-3">
        <nav class="d-flex justify-content-end" aria-label="...">
            @if( count($categories) <= 0 )
                <h6 class="container text-center font-weight-bold">-- NOT FOUND DATA --</h6>
            @endif
        </nav>
    </div>
</div>