routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\StockController as AdminStockController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\EmailNotificationController as AdminEmailNotificationController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\ShippingController as AdminShippingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\WishlistController;
use App\Http\Controllers\User\EmailNotificationController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\CategoryController;

if (App::environment('production')) {
    URL::forceScheme('https');
}


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Route Admin
 */

Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.home');

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [AdminRoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_read');

        Route::get('/create', [AdminRoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [AdminRoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_create');

        Route::put('/{id}', [AdminRoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('/{id}/edit', [AdminRoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_update');

        Route::delete('/{id}', [AdminRoleController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:role_delete');

        Route::get('/{id}', [AdminRoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_read');
    });

    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [AdminUserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_read');

        Route::get('/create', [AdminUserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::get('/{id}', [AdminUserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_read');

        Route::post('/', [AdminUserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_create');

        Route::put('/{id}', [AdminUserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('/{id}/edit', [AdminUserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_update');

        Route::delete('/{id}', [AdminUserController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:user_delete', 'check.delete.user');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [AdminCategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_read');

        Route::get('/list', [AdminCategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_read');

        Route::post('/', [AdminCategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_create');

        Route::get('/create', [AdminCategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::get('/{id}', [AdminCategoryController::class, 'show'])
            ->name('show')
            ->middleware('permission:category_read');

        Route::delete('/{id}', [AdminCategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');

        Route::put('/{id}', [AdminCategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::get('/{id}/edit', [AdminCategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_update');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [AdminProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_read');

        Route::get('/create', [AdminProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/{id}', [AdminProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_read');

        Route::post('/', [AdminProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_create');

        Route::put('/{id}', [AdminProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::get('/{id}/edit', [AdminProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_update');

        Route::delete('/{id}', [AdminProductController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:product_delete');
    });

    Route::name('stocks.')->prefix('stocks')->group(function (){
        Route::get('/', [AdminStockController::class, 'index'])
            ->name('index')
            ->middleware('permission:stock_read');
        Route::get('/create', [AdminStockController::class, 'create'])
            ->name('create')
            ->middleware('permission:stock_create');
        Route::post('/', [AdminStockController::class, 'store'])
            ->name('store')
            ->middleware('permission:stock_create');
        Route::put('/update/{id}', [AdminStockController::class, 'update'])
            ->name('update')
            ->middleware('permission:stock_update');
        Route::get('/{id}/edit', [AdminStockController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:stock_update');
        Route::get('/{id}', [AdminStockController::class, 'show'])
            ->name('show')
            ->middleware('permission:stock_read');
        Route::delete('/{id}', [AdminStockController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:stock_delete');
    });

    Route::name('coupons.')->prefix('coupons')->group(function () {
        Route::get('/', [AdminCouponController::class, 'index'])
            ->name('index')
            ->middleware('permission:coupon_read');
        Route::get('/create', [AdminCouponController::class, 'create'])
            ->name('create')
            ->middleware('permission:coupon_create');
        Route::post('/', [AdminCouponController::class, 'store'])
            ->name('store')
            ->middleware('permission:coupon_create');
        Route::put('/update/{id}', [AdminCouponController::class, 'update'])
            ->name('update')
            ->middleware('permission:coupon_update');
        Route::get('/{id}/edit', [AdminCouponController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:coupon_update');
        Route::get('/{id}', [AdminCouponController::class, 'show'])
            ->name('show')
            ->middleware('permission:coupon_read');
        Route::delete('/{id}', [AdminCouponController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:coupon_delete');
    });

    Route::name('emails.')->prefix('emails')->group(function () {
        Route::get('/', [AdminEmailNotificationController::class, 'index'])->name('index');
        Route::get('/create', [AdminEmailNotificationController::class, 'create'])->name('create');
        Route::put('/update/{id}', [AdminEmailNotificationController::class, 'update'])->name('update');
        Route::get('/{id}/edit', [AdminEmailNotificationController::class, 'edit'])->name('edit');
        Route::delete('/{id}', [AdminEmailNotificationController::class, 'destroy'])->name('destroy');
    });

    Route::name('orders.')->prefix('orders')->group(function () {
        Route::get('/', [AdminOrderController::class, 'index'])
            ->name('index')
            ->middleware('permission:order_read');
        Route::get('/create', [AdminOrderController::class, 'create'])
            ->name('create')
            ->middleware('permission:order_create');
        Route::post('/', [AdminOrderController::class, 'store'])
            ->name('store')
            ->middleware('permission:order_create');

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Stock extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'stocks';

    protected $fillable = [
        'product_id',
        'amount',
        'status',
        'note',
    ];

    public function products()
    {
        return $this->belongsTo(
            Product::class,
            'product_id',
            'id'
        );
    }

    public function getAllWithRelationship()
    {
        return $this->with('products')->get();
    }

    public function scopeWithProductName($query, $nameProduct)
    {
        return $query->when($nameProduct, function ($e) use ($nameProduct) {
            $e->orWhereHas('products', function ($q) use ($nameProduct) {
                $q->where('name', 'like', '%' . $nameProduct . '%');
            });
        });
    }

    public function scopeProductImport($query, $productId)
    {
        return $query->where('product_id', $productId)
            ->where('status', config('constants.stock.status.import.key'))
            ->pluck('amount')->toArray();
    }

    public function scopeProductExport($query, $productId)
    {
        return $query->where('product_id', $productId)
            ->where('status', config('constants.stock.status.export.key'))
            ->pluck('amount')->toArray();
    }
}

app/Http/Controllers/Admin/StockController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Stock\StoreStockRequest;
use App\Services\StockService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StockController extends Controller
{
    protected StockService $stockService;

    /**
     * @param StockService $stockService
     */
    public function __construct(StockService $stockService)
    {
        $this->stockService = $stockService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $stocks = $this->stockService->search($request);
        return view('admin.stocks.index', compact('stocks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.stocks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreStockRequest $request
     * @return RedirectResponse
     */
    public function store(StoreStockRequest $request)
    {
        $this->stockService->create($request);
        return redirect()->route('stocks.index')->with('message', 'Create Stock Success!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $stock = $this->stockService->findWithRelationship($id);
        return view('admin.stocks.show', compact('stock'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit(int $id)
    {
        $stock = $this->stockService->findById($id);
        return view('admin.stocks.edit', compact('stock'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreStockRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(StoreStockRequest $request, int $id)
    {
        $this->stockService->update($request, $id);
        return redirect()->route('stocks.index')->with('message', 'Update Stock Success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy(int $id)
    {
        $this->stockService->softDelete($id);
        return redirect()->route('stocks.index')->with('message', 'Delete Stock Success!');
    }
}

resources/views/admin/stocks/create.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'stocks'
])
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-header">
                        <h2 class="mb-0 text-dark text-center">
                            Create Stock
                        </h2>
                    </div>
                    <div class="card-body">
                        <form enctype="multipart/form-data" action="{{ route('stocks.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <div class="d-flex">
                                    @foreach(config('constants.stock.status') as $key => $name)
                                        <div class="form-check form-check-inline d-flex align-items-center">
                                            <input class="form-check-input" type="radio" name="status"
                                                   {{ old('status') == config('constants.stock.status.'.$key.'.key') ? 'checked' : '' }}
                                                   id="inlineRadio1" value="{{ config('constants.stock.status.'.$key.'.key') }}">
                                            <label class="text-dark m-0">
                                                <h6 class="m-0">
                                                    {{ config('constants.stock.status.'.$key.'.name') }}
                                                </h6>
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                @error('status')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            <div class="row mt-2">
                                <div class="form-group col-8">
                                    <label class="text-dark">
                                        <h6 class="m-0">Name product <span class="text-danger">*</span></h6>
                                    </label>
                                    <select name="product_id" class="form-control pl-1 mr-2" id="select-product">
                                        <option value=""></option>
                                        @foreach($products as $product)
                                            <option {{ old('product_id') == $product->id ? 'selected' : '' }}
                                                value="{{ $product->id }}">
                                                {{ $product->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('product_id')
                                        <span class="alert-danger" role="alert">
                                            {{$message}}
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group mb-3 col-4">
                                    <label class="text-dark">
                                        <h6 class="m-0">Amount <span class="text-danger">*</span></h6>
                                    </label>
                                    <input type="number" class="form-control" name="amount"
                                           value="{{ old('amount') }}"
                                           placeholder="Amount">
                                    @error('amount')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group mb-3">
                                <label class="text-dark">
                                    <h6 class="m-0">Note</h6>
                                </label>
                                <textarea class="form-control" rows="3" name="note"></textarea>
                            </div>
                            <div>
                                <a href="{{ route('stocks.index') }}" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#select-product').select2({
            width: '100%',
            placeholder: "--Select Product--",
        });
    </script>
@endpush

resources/views/admin/stocks/edit.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'stocks'
])
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-header">
                        <h2 class="mb-0 text-dark text-center">
                            Edit Stock
                        </h2>
                    </div>
                    <div class="card-body">
                        <form enctype="multipart/form-data" action="{{ route('stocks.update', $stock->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <div class="d-flex">
                                    <div class="form-check form-check-inline d-flex align-items-center">
                                        <input class="form-check-input" type="radio" name="status" checked
                                               id="inlineRadio1" value="{{ $stock->status == 1 ? config('constants.stock.status.import.key') : config('constants.stock.status.export.key')}}">
                                        <label class="text-dark m-0">
                                            <h6 class="m-0">
                                                {{ $stock->status == 1 ? config('constants.stock.status.import.name') : config('constants.stock.status.export.name')}}
                                            </h6>
                                        </label>
                                    </div>
                                </div>
                                @error('status')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            <div class="row mt-2">
                                <div class="form-group col-8">
                                    <label class="text-dark">
                                        <h6 class="m-0">Name product <span class="text-danger">*</span></h6>
                                    </label>
                                    <select name="product_id" class="form-control pl-1 mr-2" id="select-product">
                                        <option value=""></option>
                                        @foreach($products as $product)
                                            <option {{ old('product_id', $stock->product_id) == $product->id ? 'selected' : '' }}
                                                    value="{{ $product->id }}">
                                                {{ $product->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('product_id')
                                        <span class="alert-danger" role="alert">
                                            {{$message}}
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group mb-3 col-4">
                                    <label class="text-dark">
                                        <h6 class="m-0">Amount <span class="text-danger">*</span></h6>
                                    </label>
                                    <input type="number" class="form-control" name="amount"
                                           value="{{ old('amount', $stock->amount) }}"
                                           placeholder="Amount">
                                    @error('amount')
                                    <span class="alert-danger" role="alert">
                                        {{$message}}
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group mb-3">
                                <label class="text-dark">
                                    <h6 class="m-0">Note</h6>
                                </label>
                                <textarea class="form-control" rows="3" name="note">{!! old('note', $stock->note) !!}</textarea>
                            </div>
                            <div>
                                <a href="{{ route('stocks.index') }}" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#select-product').select2({
            width: '100%',
            placeholder: "--Select Product--",
        });
    </script>
@endpush

resources/views/admin/stocks/show.blade.php
@extends('layouts.admin.app', [
    'class' => '',
    'elementActive' => 'stocks'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div>
                                {{ $stock[0]->products->name }}
                                {{ $stock[0]->amount }}
                                {{ $stock[0]->note }}
                                {{ $stock[0]->status }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection